import yaml

from snakemake.utils import min_version, validate

min_version("9.19")

# !!!!! IMPORTANT !!!!!
# Define pathvars for all user resource files and result files
# This allows users to re-wire how the module is used in their workflow with ease.
pathvars:
    # User resources
    shapes="<resources>/user/{shapes}/shapes.parquet",
    powerplants="<resources>/user/{shapes}/powerplants.parquet",
    # Module results
    statistics="<results>/{shapes}/statistics/generation.parquet",
    disaggregated_inflow="<results>/{shapes}/disaggregated/inflow_mwh.parquet",
    aggregated_cf_timeseries="<results>/{shapes}/aggregated/{plant_type}_cf.parquet",


# Load the example configuration. This will be overridden by users.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)


# Add all your includes here.
include: "rules/_utils.smk"
include: "rules/automatic.smk"
include: "rules/statistics.smk"
include: "rules/basins.smk"
include: "rules/powerplants.smk"


# Add all files to be delivered alongside the workflow here
workflow.source_path("scripts/_plots.py")
workflow.source_path("scripts/_schemas.py")

# Run additional configuration validation
validate_year_config()


rule all:
    message:
        "ERROR: Invalid `rule all:` call"
    default_target: True
    output:
        "INVALID",
    log:
        stderr="<logs>/all.stderr",
    conda:
        "envs/shell.yaml"
    shell:
        'echo "This workflow must be called as a snakemake module." > {log.stderr}'
