# Changes here will be overwritten by Copier
# !!!!! DO NOT MANUALLY MODIFY THIS FILE !!!!!
_commit: v1.0.3
_src_path: https://github.com/modelblocks-org/data-module-template.git
authors:
-   email: 17178478+brynpickering@users.noreply.github.com
    family_name: Pickering
    given_name: Bryn
-   email: tim.troendle@usys.ethz.ch
    family_name: Troendle
    given_name: Tim
-   email: i.ruizmanuel@tudelft.nl
    family_name: Ruiz Manuel
    given_name: Ivan
github_org: modelblocks-org
license: Apache-2.0
maintainers:
-   email: i.ruizmanuel@tudelft.nl
    family_name: Ruiz Manuel
    given_name: Ivan
module_code_name: module_hydropower
module_description: A module to calculate hydropower inflow timeseries for facilities
    around the globe, based on Euro-Calliope methods.
module_human_name: Hydropower timeseries
