# Emulate a user configuring the module.
configfile: workflow.source_path("./test_config.yaml")


# Import the module and configure it.
# `snakefile:` specifies the module. It can use file paths and special github(...) / gitlab(...) markers
module module_hydropower:
    snakefile:
        "../../workflow/Snakefile"
    config:
        config["module_hydropower"]
    prefix:
        "results/integration_test/"


# rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_hydropower as module_hydropower_*


# Request something from the module
rule all:
    message:
        "Generate CF timeseries for a small country."
    default_target: True
    input:
        "results/integration_test/results/MNE/aggregated/reservoir_cf.parquet",
        "results/integration_test/results/MNE/aggregated/run_of_river_cf.parquet",
