# A minimal example of how to configure this module
pfafstetter_level: "06"
years:
  start: 2015
  end: 2015
powerplants:
  technology_mapping:
    run_of_river: "run of river"
    reservoir: "reservoir"
  basin_adjustment:
    buffer_radius: 1000  # epsg:3857 is in meters
    max_outside: 50
    max_dropped: 30
crs:
  projected: "epsg:3857"
  geographic: "epsg:4326"
smoothing_hours: "168h"
